### ISSUE TITLE
Error in conda environment creation

### ISSUE THREAD

**Issue by Rajarshi1001** [maxfrei750/paddle#1]
While setting up the repository in __Anaconda Prompt__, the line
` conda env create --file environment.yaml`
initally shows `Collecting package metadata` which gets completed soon but the `solving environment` step takes a huge amount of time.

Could you please provide some help in setting it up and using this model?

**Comment by maxfrei750** [comment]
I tried to create the environment from scratch myself and faced the same issue. I think that it would just take _very_ long for conda to create the environment, but still it is a little strange, since it used to work rather quickly. That being said, while I was looking for potential reasons, I found that many people have [similar problems with conda](https://stackoverflow.com/a/70147535/11652760) and some of them suggest using [mamba](https://github.com/mamba-org/mamba) as a drop-in replacement. I tested it, and it created the environment in minutes using `mamba env create --file environment.yaml`. Maybe you can try it out as well and if it works for you too, then I'll add a note to the readme.

**Comment by Rajarshi1001** [comment]
Actually it got installed successfully, but there was an issue named `DLL load failed while importing win32api: The specified procedure could not be found.` while running `jupyter lab`

**Comment by Rajarshi1001** [comment]
Also while running each of the notebooks, there was an error showing `no module paddle`.

**Comment by maxfrei750** [comment]
> Actually it got installed successfully

Glad to hear that!

Please open two separate issues for the two other problems. It makes it easier for others with the same problem to find the solutions in the future. Closing this issue now.
